version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-first-lambda-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2zcdcsqb6ce1"
s3_prefix = "my-first-lambda-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
